services:
  l2:
    image: offchainlabs/nitro-node:v3.5.2-33d30c0
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "./nodeConfig.json:/config/nodeConfig.json"
      - ${L2_DATA}:/home/user/.arbitrum
    entrypoint:
      - "/usr/local/bin/nitro"
      - --conf.file=/config/nodeConfig.json
      - --node.staker.enable
      - --node.staker.strategy=Watchtower
      - --execution.forwarding-target=wss://symbiosis.calderachain.xyz/ws
      - --node.feed.input.url=wss://symbiosis.calderachain.xyz/feed
      - --parent-chain.connection.url=${ETHEREUM_RPC}
      - --parent-chain.blob-client.beacon-url=${ETHEREUM_BEACON_RPC}
      
      
